# Firestore Emulator Server Configuration (Test)

# Server host
host: localhost

# Server port
port: 3333

# Default project ID
projectId: test-project

# Logs configuration
logs:
  verboseGrpcLogs: true
